namespace Advertise.Application.NutritionistBannerAdvertises.V1.Commands.ChangeNutritionistBannerAdvertiseStatus;

public record ChangeNutritionistBannerAdvertiseStatusCommand(string Id, AdvertiseStatus Status) : IRequest;