namespace Identity.V2.Domain.Aggregates.UserAggregate;

[BsonIgnoreExtraElements]
[RuntimeVersion("0.1.6")]
//[StartUpVersion("0.1.6")]

[CollectionLocation("users","default")]
public class User : UserAggregateRoot, IDocument
{
    public Language Language { get; set; }
    public DateTimeOffset? LastSeenTime { get; set; }
    public bool IsBlocked { get; set; }
    public DateTime RegisterDate { get; set; }
    public ObjectId CountryId { get; set; }

    public ObjectId StateId { get; set; }

    public ObjectId CityId { get; set; }
    //public ObjectId UserProfileId { get; set; }
    public bool IsActive { get; set; }
    public string ReferralCode { get; set; } = string.Empty;
    public string? ReferralInviter { get; set; }
    public int ReferralCountBuy { get; set; }
    public string ConfirmCode { get; set; } = string.Empty;
    public DateTime ConfirmCodeExpireTime { get; set; }
    public DayOfWeek StartOfWeek { get; set; }
    public string AutoGeneratedPassword { get; set; } = string.Empty;
    public bool IsComplete { get; set; }
    public UserProfile UserProfile { get; set; } = new UserProfile(ObjectId.GenerateNewId().ToString());
    public NutritionistProfile NutritionistProfile { get; set; } = new(ObjectId.GenerateNewId().ToString());
    public List<DeviceInformation> DeviceInformation { get; set; } = new List<DeviceInformation>();
    public UserStatus Status { get; set; }

    #region Add to user micro

    // public int? NutritionDietCategoryId { get; set; }
    // public int? NormalDietCategoryId { get; set; }

    #endregion

    [BsonElement("Version")] public DocumentVersion Version { get; set; } = new DocumentVersion("0.1.6");
}