namespace Advertise.Application.NutritionistBannerAdvertises.V1.Commands.IncreaseNutritionistBannerAdvertiseViewCount;

public record IncreaseNutritionistBannerAdvertiseViewCountCommand(string Id) : IRequest;