namespace Advertise.Application.NutritionistBannerAdvertises.V1.Commands.IncreaseNutritionistBannerAdvertiseClickCount;

public record IncreaseNutritionistBannerAdvertiseClickCountCommand(string Id) : IRequest;