namespace Identity.V2.Application.Users.V1.Queries.CheckUserExitsByUsernameAndAutoGeneratedPassword;

public class CheckUserExitsByUsernameAndAutoGeneratedPasswordQueryValidator : AbstractValidator<CheckUserExitsByUsernameAndAutoGeneratedPasswordQuery>
{
    public CheckUserExitsByUsernameAndAutoGeneratedPasswordQueryValidator()
    {
        RuleFor(x => x.Username)
            .NotEmpty().WithMessage("Username can not be empty")
            .NotNull().WithMessage("Username can not be null");

        RuleFor(x => x.AutoGeneratedPassword)
            .NotEmpty().WithMessage("AutoGeneratedPassword can not be empty")
            .NotNull().WithMessage("AutoGeneratedPassword can not be null");
        
    }
}