namespace Identity.V2.Application.Users.V1.Queries.CheckUserExitsByUsernameAndAutoGeneratedPassword;

public class CheckUserExitsByUsernameAndAutoGeneratedPasswordQueryHandler: IRequestHandler<CheckUserExitsByUsernameAndAutoGeneratedPasswordQuery, bool>
{
    private readonly IUnitOfWork _uow;

    public CheckUserExitsByUsernameAndAutoGeneratedPasswordQueryHandler(IUnitOfWork uow)
    {
        _uow = uow;
    }

    public async Task<bool> Handle(CheckUserExitsByUsernameAndAutoGeneratedPasswordQuery request, CancellationToken cancellationToken)
    {
        var result = await _uow.UserGenericRepository<User>()
            .AnyAsync(x =>
                x.NormalizedUserName == request.Username.ToUpper() &&
                x.AutoGeneratedPassword == request.AutoGeneratedPassword, cancellationToken).ConfigureAwait(false);
        return result;
    }
}